name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Solution
      run: |
        C:/"Program Files"/"Microsoft Visual Studio"/2022/Enterprise/Common7/IDE/devenv MhyProt2Drv.sln /Build Release
    - name: Deploy to artifact
      uses: actions/upload-artifact@v1
      with:
        name: MhyProt2Drv
        path: bin\Release
